Events page
traPtitech/traPortfolio-Dashboard pull request #140
Opened 2023-12-03 08:46 UTC by Pugma

close #6

2023-12-05 15:16 UTC, mehm8128 requested changes
PRありがとうございます！
まだある気もしてますが一旦ここらへん確認お願いします:pray:

2023-12-05 15:16 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +            :class="$style.eventLevelMenuButton"
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
これとかも使ってなさそうです

2023-12-05 15:16 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +        @click="displayMenu = displayMenu ? false : true"
![must](https://img.shields.io/badge/review-must-red.svg)
アイコンを押したときにメニューが開かない問題ですが、`clickOutside`が対象の要素がクリックされた要素を含んでいる場合でもなぜかif文の中に入ってしまっていそうで、実際にはメニューが開かないのではなくて、`@click`でメニューが開かれる→`clickOutside`ですぐ閉じる、が発生してしまっていそうです

バグの原因は分からなかったのですが、一応以下でも解決します
`@click`を関数に切り出して、以下のようにする
```typescript
const toggle = () => {
  setTimeout(() => {
    displayMenu.value = !displayMenu.value
  }, 0)
}
```
こうすることで、`toggle`が`clickOutside`よりも後に呼ばれるようになります

でももっと簡単な方法があって、`@click`を`@click.stop`にするとクリックイベントがそれより上にバブリングされなくなるので、`clickOutside`内の条件分岐もいらなくなるはずです
参考:
https://developer.mozilla.org/ja/docs/Web/API/Event/stopPropagation
https://ja.vuejs.org/guide/essentials/event-handling#event-modifiers
`stopPropagation`をVueでは`.stop`で簡単に書けるようになってます

2023-12-05 15:16 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +})
![should](https://img.shields.io/badge/review-should-important.svg)
ドキュメントではDOMイベントリスナーのクリーンナップは`onUnmounted`を使うって書いてあるのでこっち使ってほしいです(`onBeforeUnmount`でなんか問題があるのかと言われたらあんまり問題はない気がしますが)
https://ja.vuejs.org/api/composition-api-lifecycle#onunmounted

2023-12-05 16:37 UTC, Pugma commented on src/pages/Events.vue
> +const searchQuery = ref<string>('')
特に特殊な型でなければ型推論に頼っちゃって大丈夫なんですね
明示するほうが可読性高そうだな〜って思ってました

2023-12-05 16:38 UTC, SSlime-s commented on src/components/Events/EventItem.vue
> +        @click="displayMenu = displayMenu ? false : true"
FYI: click によって
1. `displayMenu` が `true` に
2. アイコンが `v-if` によって書き換わる
3. `contains` の条件が満たされなくなる
4. `button` の '中' にあるとみなされなくて、閉じる

で閉じてしまっていると思います
(例えば、現状の実装に寄せるなら、`event.target.contains` で判定するのではなく、`e.composedPath().includes(event.value)` とかにすると正常に動作します)

2023-12-05 21:32 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +        @click="displayMenu = displayMenu ? false : true"
なるほどです
書くの忘れてたのですが、クリックしたときに矢印アイコンがくるっと回ってひっくり返るようなアニメーションもできればつけてほしいので、それやるならアイコン同じやつでCSSだけ変えるので条件式は今のままでいいかもですね

2023-12-09 14:00 UTC, mehm8128 commented
@Pugma (一応)再レビューしてよさそうなタイミングになったら再レビュー依頼お願いします:pray:(ハッカソン期間なのですぐにできるか微妙ですが)
![image](https://github.com/traPtitech/traPortfolio-Dashboard/assets/83744975/8a66fa98-88cd-4989-ab63-a027a8666bd2)

2023-12-27 12:42 UTC, mehm8128 requested changes
もうちょっとお願いします:pray:

また、前回のやつ1つ見逃してそうな気するので確認してみてください:eyes:
https://github.com/traPtitech/traPortfolio-Dashboard/pull/140#discussion_r1415725469

2023-12-27 12:42 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +    @click="router.push({ name: 'Event', params: { id: event.id } })"
![should](https://img.shields.io/badge/review-should-important.svg)
a11y上の理由から、リンクはできるだけ`router.push`を使うより、`router-link`を使ってほしいです

2023-12-27 12:42 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +    v-if="eventDetail.eventLevel === eventLevel"
ここで分岐するよりも、`Events.vue`の`<li v-for="event in events`で回す`events`を`filteredEvents`みたいに既にフィルタリングされているものにした方がよさそうです

2023-12-27 12:42 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +    @click="router.push({ name: 'Event', params: { id: event.id } })"
![must](https://img.shields.io/badge/review-must-red.svg)
あと、右側の状態変更ボタンを押したときに押す場所によってはリンク遷移しちゃうので、右側はリンクにせずに、前に貼った画像の位置くらいで大丈夫です↓
![image](https://github.com/traPtitech/traPortfolio-Dashboard/assets/83744975/f6a4ad5c-ae5a-44a9-bc0f-f39b5ad9a695)

2023-12-27 12:42 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +          <p :class="$style.statusName">
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
1つのspanにまとめられそうです？(ちなみに、buttonタグの中にpタグを入れるのは許可されていないです(別のところでやっちゃってるところあった気がするけどいつか直します))

2023-12-27 12:42 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +  transition: 0.5s;
![good](https://img.shields.io/badge/review-good-success.svg)
アニメーションついてていい感じです

2023-12-27 12:42 UTC, mehm8128 commented on src/components/UI/EventTypeAccordion.vue
> +  set: v => emit('update:modelValue', getEventLevelFromValue(v) ?? '匿名公開')
![should](https://img.shields.io/badge/review-should-important.svg)
多分公開の方がよく使われる気がするので、`??`の後ろは匿名公開じゃなくて公開の方がよさそうです

ただ、EventLevelは0~2の数値のはずなので、`'公開'`なら`1`みたいな数値でデフォルト値指定してほしいです

2023-12-27 12:42 UTC, mehm8128 commented on src/pages/Events.vue
> +const eventType = ref(0)
![should](https://img.shields.io/badge/review-should-important.svg)
ここも同様にデフォルトは`1`がいい気がします

2024-01-01 10:29 UTC, Pugma commented on src/components/Events/EventItem.vue
> +    v-if="eventDetail.eventLevel === eventLevel"
ここ色々検討してみたんですが、先にフィルタリングしようとするとEvent詳細情報まで取得するしかなくって、それを全部に実施するのはそこそこつらいなぁ、といった感じです
現状`EventItem`内で個々にAPIを叩いてなんとか実装していますが、基本情報に公開範囲も含めておくようにしていただけるほうが構造が簡素になるかと思います

2024-01-02 04:02 UTC, Pugma commented on src/components/Events/EventItem.vue
> +    v-if="eventDetail.eventLevel === eventLevel"
@mehm8128

2024-01-02 04:19 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +    v-if="eventDetail.eventLevel === eventLevel"
あー、一覧で取ってきたら公開レベルが入ってないのか
入ってた方が便利だと思うので、サーバーのメンバーに相談して入れてもらうことを検討してもらうのがよさそうです

2024-01-02 04:22 UTC, Pugma commented on src/components/Events/EventItem.vue
> +    v-if="eventDetail.eventLevel === eventLevel"
:haakusimasita:

2024-01-03 07:57 UTC, Pugma commented on src/components/Events/EventItem.vue
> +}
@mehm8128 mutateの導入まではやったんですが、computedにしたら変数の更新処理が不要になるというのがよく分からなかったです…

2024-01-03 08:06 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +}
多分getEventsしたやつを親コンポーネントから受け取って使ってる場合に、`mutate()`したらそれが更新されるので`eventLevelValue`もそこから自動で計算できるから`ref`で手動で変えるんじゃなくて`computed`でよさそう、みたいなこと言いたかったんだった気がします
ただ、今はgetEventでこのコンポーネントで取得したやつを使ってるので多分できないので、`ref`のままでよさそうです:pray:

2024-01-08 02:48 UTC, mehm8128 commented
これってサーバーの変更が必要な箇所以外もうレビューしてOKな状態だったりするんでしたっけ？

2024-01-08 06:39 UTC, mehm8128 commented
OKです、じゃあそこ以外レビューしておきますー

2024-01-08 09:01 UTC, mehm8128 commented on src/components/Events/EventItem.vue
> +}
![should](https://img.shields.io/badge/review-should-important.svg)
hover時に角丸になっていないやつ、`Events.vue`の`.eventList`についている↓をここに移動するだけで直るっぽいので直しておいてほしいです:pray:
```
  &:hover {
      background-color: $color-background-dim;
    }
```

2024-01-20 01:45 UTC, Pugma commented
close #155

2024-01-20 15:20 UTC, mehm8128 approved these changes
よさそうです！ありがとうございました

2024-01-20 15:23 UTC, merged