traPブログについての説明を追記
traPtitech/traPortfolio-Dashboard pull request #279
Opened 2024-06-08 12:56 UTC by mehm8128

close https://github.com/traPtitech/traPortfolio-Dashboard/issues/273
Blogを選択したときだけ表示でもいいような気もする

2024-06-10 08:16 UTC, Pugma requested changes
ありがとうございます！
一点だけ確認をお願いします

2024-06-10 08:16 UTC, Pugma commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
このときvalidationがおかしくなっていそうです
`https://{ なんか }`
を入れると「追加」ができるようになる感じです

そもそも入力欄を消しちゃってもいいのでは…？
という気がします

2024-06-10 12:28 UTC, mehm8128 commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
よく分からなかったのですが、各フィールドに何を入れたときにどういうバリデーションエラーになってほしいってことですか？

>そもそも入力欄を消しちゃってもいいのでは

の入力欄ってサービス名に何を選んだときのどれのことですか？

2024-06-11 09:21 UTC, Pugma commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
Blogを追加する際のURL validationについて言及してました
ここで僕が気になっているのは
- URL欄を作る必要がないのではないか
    - フロントエンド側ですでにUserID情報は持っているので、改めて入力させるとミスタイプの可能性もあります
- もしURLを作るにしても、validationがおかしいのではないか
    - `https://foo` `https://hoge`でも通ってしまうので、欄を用意するなら`https://trap.jp/author/{ なにか }`でvalidationしたほうがよさそう

ってここまで書いていて思ったんですが、この`Blog`って個人ブログのことを指してますか？
それだとしても`HomePage`と若干競合してそうだったのでtrapのものだと勝手に思ってしまってました
URLを
<img width="1019" alt="image" src="https://github.com/traPtitech/traPortfolio-Dashboard/assets/132571355/65978b63-4561-48da-8b62-c042a05dc452">

2024-06-11 09:23 UTC, mehm8128 commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
HomePageはポートフォリオとかで、Blogはtrap.jpではなくて個人ブログのこと(trap.jpに限らないブログだったけどtrap.jpを別で用意するようにしたのでtrap.jp以外のブログ)を想定してると思います

2024-06-11 09:24 UTC, mehm8128 commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
ポートフォリオって言ってブログのリンク貼ってる人とかポートフォリオとブログが合体してる人とかもいるので確かにBlogはいらないような気もしてきました
別で持ってる人のことも考えると、HomePageを複数設定できるようにしておけばいいですかね

2024-06-11 09:30 UTC, mehm8128 commented on src/pages/UserAccountNew.vue
>            v-model="formValues.url"
OKです、そうします(多分どこかのPRでHomePageが複数選択できちゃうバグ直してるのですが、そっちにも影響するので見かけたらちょっと待ってもらえると助かります)
そうですね、traPのIDに紐づいて既に公開されているものなので、全員設定の余地なく公開にしています

2024-06-12 09:08 UTC, Pugma commented
@mehm8128
このPRってこの状態でマージしたいんでしたっけ？

2024-06-12 09:29 UTC, mehm8128 commented
多分マージせずにcloseでいいかなーってなってます

2024-06-12 09:30 UTC, Pugma commented
承知しました！
じゃあcloseをお願いします

2024-06-12 09:31 UTC, closed without merging