Feat/event modal
traPtitech/traPortfolio-Dashboard pull request #82
Opened 2023-09-14 09:22 UTC by helgev-traP

```./src/components/Events/EventModal.vue``` の中に作ってます。

propsで```openStatus```を受け取って```update-public-status```を引数付きで発火します。

2023-09-16 09:03 UTC, mehm8128 requested changes
最初なのでちょっと多めですが、確認してほしいです！
分からないところとかあればまた聞いてください

2023-09-16 09:03 UTC, mehm8128 commented on src/components/Events/EventModal.vue
> +  <dev :class="$style.eventModalBox">
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
```suggestion
  <div :class="$style.eventModalBox">
```

2023-09-16 09:03 UTC, mehm8128 commented on src/components/Events/EventModal.vue
CSSのclass名とかも合わせて直してほしいです

2023-09-16 09:03 UTC, mehm8128 commented on src/components/Events/EventModal.vue
> +      ]"
ちょっとここもうちょいいい書き方ありそうなのですが、すぐに出てこないのでもうちょっと考えさせてください

2023-09-16 09:03 UTC, mehm8128 commented on src/components/Events/EventModal.vue
> +      <p :class="$style.discription">ポートフォリオにて公開します</p>
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
ここらへんの文章、[僕のPR](https://github.com/traPtitech/traPortfolio-Dashboard/pull/76/files#diff-602e8cf9527b32b7d39e3800266ad8f61156a6faab94b7fa70abe7660a6397ad)でいい感じに定数化しているので、これそのままコピペして使っちゃってください(本当は僕のをさっさとマージできたらいいのですが...)

2023-09-16 09:28 UTC, mehm8128 commented on src/components/Events/EventModal.vue
> +      ]"
今の公開状態のボタンは押せなくてよさそうなので、`:disabled="eventLevel === 1"`みたいにしておいて、CSSで`&:disabled`にdisabledなときの色(primary colorとか)を指定するのはどうですか？:eyes:

2023-09-16 16:08 UTC, mehm8128 reviewed
あ、あとPRの説明文に`close https://github.com/traPtitech/traPortfolio-Dashboard/issues/52`とかって書くとissueを紐付けられるので、お願いしますー(PRをマージしたときに自動でissueもclose されるようになります)

2023-10-10 07:02 UTC, mehm8128 commented on src/components/Events/EventModal.vue
> +      <p :class="$style.discription">ポートフォリオにて公開します</p>
PRマージできたので、mainをrebaseとかmergeとかして使ってみてください:+1:

2023-11-02 16:28 UTC, mehm8128 reviewed
大体よさそうなのですが、細かいところ指摘しました
確認お願いします:pray:

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +        :class="[$style.eventLevelMenuButton]"
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
```suggestion
        :class="$style.eventLevelMenuButton"
```

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +        <p :class="$style.description" style="white-space: pre-wrap">
![should](https://img.shields.io/badge/review-should-important.svg)
改行の処理、`style`じゃなくて`.description`のCSSの方に書いてほしいです:pray:

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    <div v-for="[level, detail] in eventLevels" :key="level">
![good](https://img.shields.io/badge/review-good-success.svg)
`v-for`で回してるのいい感じに書けててgoodです

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    font-weight: 400;
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
大体の場合、`font-weight: 400;`はデフォルトなので書かなくてもよさそうです

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    font-weight: 600;
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
太くするのは数値じゃなくて`font-weight: bold;`で指定したいです(数値としては700の扱いになります: https://developer.mozilla.org/ja/docs/Web/CSS/font-weight)

理由としては、多くのフォントで600など細かい太さがサポートされてなくて、↑に貼ったリンクの通り、600と書いたたら700の太さで表示されることが多いからです

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    font-size: 16px;
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
これも、font-sizeはデフォルトが16pxなので書かなくてもよさそうです

2023-11-02 16:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    font-size: 12px;
![should](https://img.shields.io/badge/review-should-important.svg)
a11y的な理由により、ブラウザのフォントサイズを変えたときにいい感じの表示になるように、`rem`で指定したいです。今回の場合は0.75remですかね
figmaのdevモードで設定すればremの値で表示されるようになるので、そっちで見てみるといいです

2023-11-02 16:30 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +        <p :class="$style.statusName">{{ detail.label }}</p>
実はbuttonタグの中、headingタグだけじゃなくてpタグも入れられないことに気づいたのですが、一旦スルーで大丈夫です:pray:

2023-11-10 01:52 UTC, mehm8128 reviewed
1箇所だけ:pray:

次回からでいいのですが、PRの説明文はPRの概要とか相談したい点とかを書く場所にしたいので、レビューのたびに修正内容とかを追加する必要はないです
修正内容はcommit messageに書いてもらってるので、そこで分かります:+1:

あと、しゅーまいさんが出してくれた修正とconflictしてる箇所があるのですが、大変そうなのであとで確認します
できそうなら直してもらいますが、難しそうなら僕が直しちゃうかもです

2023-11-10 01:52 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +        <p :class="$style.description" style="">
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
`style`属性不要になったので完全に消しておいてほしいです

2023-11-10 02:18 UTC, helgev-traP commented
あ、消し忘れてたので消します。
conflictのやつは```\n```追加するだけなのでしゅーまいさんのやつを取ってきます
main -> Feat/event modalにマージしてこちらでconflictを解消するのでいいですか

2023-11-10 02:21 UTC, mehm8128 commented
conflictはデータ構造変わったのでコンポーネントで使う型とかももしかしたら変えないといけないかもで、帰るまでちゃんと見れないので夕方までには結論出します:pray:

2023-11-10 03:18 UTC, SSlime-s commented
1. Props と Emits で `EventLevel` を受け取るのではなく、`EventLevelValue` を受け取るようにする
    もしくは、Props で受け取った `EventLevel` を `eventLevelValueMap` と `computed` を使って、component 内で `EventLevelValue` にしたものを持つ (この場合は emit する際は `getEventLevelFromValue` で `value -> level` をする)
2. `v-for` では `v-for="[level, detail] in Object.entries(eventLevels)` のように `eventLevels` を `Object.entries` で配列にしたものを使う
    (上記の例だと `level` には `EventLevelValue` が入ることになります)
4. v-for 内の disabled の判定には 1. で `EventLevelValue` にしたものと `level` を比較する

と動くと思います

2023-11-10 05:26 UTC, mehm8128 commented
↑らしいのですができそうですか？難しそうならさっきの`style`消すやつだけやってもらえればconflict解消は僕がcommit作ります

2023-11-10 09:34 UTC, helgev-traP commented
やってみます

2023-11-11 13:57 UTC, helgev-traP commented
やってみました
一応動いてるんですがもしかしたら遠回りしてるかもしれないです

2023-11-11 14:28 UTC, mehm8128 reviewed
大体よさそうですがちょっとだけ:pray:

2023-11-11 14:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +    <div v-for="[key, value] in Object.entries(eventLevels)" :key="key">
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
`key`と`value`じゃなくて変更前のような命名でよさそうです

2023-11-11 14:28 UTC, mehm8128 commented on src/components/Events/EventLevelMenu.vue
> +  (e: 'update-public-status', value: EventLevelValue): void
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
今更だけどここ、propsと合わせて`update-event-level`の方がよさそうです

2023-11-11 14:48 UTC, SSlime-s commented on src/components/Events/EventLevelMenu.vue
> +        @click="emit('update-public-status', eventLevelValueMap[value.value])"
`key` が `EventLevelValue` に相当するので、ここは単に `key` だけで大丈夫です :+1:
(`Object.entries` の型定義が弱くて key が string に推論されちゃうので、 `as EventLevelValue` が必要になっちゃうけど)
```suggestion
        @click="emit('update-public-status', key as EventLevelValue)"
```

一応
```ts
type Entries<T extends Record<PropertyKey, unknown>, Keys = keyof T> = Keys extends keyof T ? [Keys, T[Keys]][] : never
```
とかを定義して、`Object.entries(eventLevels) as Entries<typeof eventLevels>` とかやる方法もあるにはあるんですがそこまではしなくていいかな

2023-11-11 14:53 UTC, SSlime-s commented on src/components/Events/EventLevelMenu.vue
> +        @click="emit('update-public-status', eventLevelValueMap[value.value])"
手っ取り早く治すために `as EventLevelValue` って書いちゃったんですが、厳密に (というか変更に強く) 書くなら `keyof typeof eventLevels` 使って
```suggestion
        @click="emit('update-public-status', key as keyof typeof eventLevels)"
```
って書いたほうがいいです 🤟

2023-11-12 03:30 UTC, mehm8128 approved these changes
ありがとうございます！
lintのエラー出てるのだけ直してもらえればマージしてOKです

2023-11-13 09:05 UTC, helgev-traP commented
これって自分でマージしちゃっていいんですか？

2023-11-13 10:05 UTC, mehm8128 commented
OKです！

2023-11-13 11:42 UTC, merged